resolver: nightly-2019-12-18
packages:
- .
- hie-plugin-api

extra-deps:
# - ./submodules/HaRe
- ./submodules/cabal-helper
- ./submodules/ghc-mod/ghc-project-types
- ./submodules/apply-refact
- hie-bios-0.3.2
- bytestring-trie-0.2.5.0
- constrained-dynamic-0.1.0.0
- fclabels-2.0.3.3
- floskell-0.10.2
- fold-debounce-0.2.0.9
- haddock-api-2.23.0
- haddock-library-1.8.0
- hoogle-5.0.17.13
- hsimport-0.11.0
- monad-dijkstra-0.1.1.2

flags:
  haskell-ide-engine:
    pedantic: true
  hie-plugin-api:
    pedantic: true


# allow-newer: true

nix:
  packages: [ icu libcxx zlib ]

concurrent-tests: false
